### ISSUE TITLE
Console example doesn't open Mission XML file

### ISSUE THREAD

**Issue by Stevod** [ugcs/ugcs-dotnet-sdk#2]
The following code in UGCS.Console Program.cs returns a null value of mission, with an exception for the importMissionResponse {"Import cannot be completed: incorrect input format. Please ensure you are importing a file generated by application."}

`    var importMissionResponse = messageExecutor.Submit<ImportMissionFromXmlResponse>(importMissionRequest);
            importMissionResponse.Wait();
            //mission contains imported mission from Demo mission.xml
            var mission = importMissionResponse.Value.Mission;`

This is using the latest version of the SDK with the following Demo Mission.xml file:

	<Version>
		<major v="2"/>
		<minor v="11"/>
		<build v="209"/>
		<component v="DATABASE"/>
	</Version>

**Comment by ayankelevich-ugcs** [comment]
Please check this example with the latest UgCS version https://www.ugcs.com/en/page/download

**Comment by Stevod** [comment]
Issue resolved following installation of v2.11 instead of 2.10 of UgCS.

Many thanks,
