### ISSUE TITLE
What cause "Not Authenticated" exception?

### ISSUE THREAD

**Issue by priya2507** [ugcs/ugcs-dotnet-sdk#3]
I tried to follow the same code procedure as mentioned. I could connect to the Server. When HCIRequest response section comes, I get to see "Not Authenticated" exception in the logs. What could be the reason? Could anyone please assist me on this?

**Comment by ayankelevich-ugcs** [comment]
Hi,

do you have UGCS desktop client and your application running at the same time? For UGCS Open license it is possible to have one client connection. So this can be the issue.

**Comment by priya2507** [comment]
Thanks for the reply. 
You are right. I could use only one client at a time. I could get authenticated now.

Could you tell me whether I can receive telemetry values with the single client? Am unable to get the vehicle details. It says typemismatch and also I could see a message saying device not registered in the logs.
